# Generated by Django 3.0.4 on 2020-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_detailed_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='day1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day5',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day6',
            field=models.CharField(max_length=200),
        ),
    ]
