# Generated by Django 3.0.4 on 2020-03-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_pessanger_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessanger_detail',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
