# Generated by Django 3.0.4 on 2020-05-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20200430_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='Balance',
            field=models.CharField(max_length=8),
        ),
    ]
